version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
      - ALLOWED_HOSTS=localhost,127.0.0.1
